dist: xenial
language: python
python:
  - '3.8'
install:
  - pip install --upgrade -r requirements.txt
  - pip install coverage django_coverage_plugin
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - django-admin.py makemigrations
  - coverage run --omit 'home/*' -m manage test
after_script:
  - coverage report
  - coverage xml
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then ./cc-test-reporter format-coverage -t coverage.py -o coverageupload; cat coverageupload; ./cc-test-reporter upload-coverage -i coverageupload;fi
env:
  global:
  - PYTHONPATH=.
  - DJANGO_SETTINGS_MODULE=testsettings
notifications:
  slack:
    secure: jJeXg3auGI/HeLNoQjMPNXe5BZ+vgLDivbS3QIleJjp4IVT0oiRWrismqqIiAitvieTFjx4OoVqWmB7WS6sFx3hiQl11rpcO016RAQOQ43bLJSvs4yjkRrgkCPCpwetaMBzF+zdnDVhK1DcCF3d5D9yCbafTLUB/4puO3eod02XUfp5M1V9qlIA9g2AAxLc3QUiBKb/qjDDrLU1jIcqtOlNAP7Aw1HI3D2H6bX8LUvET6yeJyzBGFEtP5xoggndIc+r8DPS1zAD8xOUdkefCiO7dxukzfE0YsOPwZ/oDjj35A49cgGAA9zZvFR8R2sJs347UCHDBcxNKWkU0/WmCKF06Wx3tc+dLtCUH0e0rhtroq43A7gRQbC9/VB2Xmr4+nZdHXbmhPjilvVTE6z1kuE6HwY3i+FQgkTrXrcjNGCVtbpPqj06rHTIQSQu5kVuxiKV0YDbcStKk0xDXw1yc3EIKoWGSNGjFnVFlZf7qQ/4tnXUinb6lDjBmFRoRKBjpqdzjgjn3fAKCfINSPpKT1goG32q5KCRvL0lB/LDwYwKo3p1cFr6pitcI2aQg13UBz9Si7shOUP9jpymr8gQh5DZcbtXQTtJbYFu4NjL9C/iVOZSEBxCGAr8M2+zgbcogHirLHcUwr/KgyK+qxqrJBLkvohUiqa+A9LfkJpYa/cU=
